version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/module-two"
    schedule:
      interval: "weekly"
    groups:
      module-two-specific-updates:
        applies-to: 'version-updates'
        patterns:
          - '*'
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-surefire-plugin"
        versions: [ ">3.5.2" ]
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-module-updates:
        applies-to: 'version-updates'
        patterns:
          - '*'
        update-types:
          - "minor"
          - "patch"